defaults:
  - default
  - optimizer: adam
  # - lr_scheduler: reduce_on_plateau
  - criterion: smooth_cross_entropy

_target_: src.models.segmentation.openpoints_module.OpenPointsModule

optimizer:
  lr: 0.001

net:
  NAME: BaseSeg
  encoder_args:
    NAME: PointNet2Encoder
    in_channels: 6
    width: null
    strides: [4, 4, 4, 4]
    layers: 3
    use_res: False
    mlps: [
        [[32, 32, 64]], # stage 1: 96
        [[64, 64, 128]], # stage 2: 256
        [[128, 128, 256]], # stage 3: 512
        [[256, 256, 512]],
      ] # stage 4: 1024
    radius: 0.1
    num_samples: 32
    sampler: fps
    aggr_args:
      NAME: "convpool"
      feature_type: "dp_fj"
      anisotropic: False
      reduction: "max"
    group_args:
      NAME: "ballquery"
      use_xyz: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: "relu"
    norm_args:
      norm: "bn"
  decoder_args:
    NAME: PointNet2Decoder
    fp_mlps: [[128, 128, 128], [256, 128], [256, 256], [256, 256]]
  cls_args:
    NAME: SegHead
    num_classes: 13
    in_channels: null
